version: "3"
services:
  mongo:
    container_name: mongodb-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    build: .
    image: api-container
    restart: always
    volumes:
      - ./dist:/usr/src/clean-appling/dist
    ports:
      - "8000:8000"
    links:
      - mongo
    command: npm start